In [3]:
%pip install spotipy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: spotipy in /Users/jhk/Library/Python/3.9/lib/python/site-packages (2.23.0)
Requirement already satisfied: six>=1.15.0 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from spotipy) (1.15.0)
Requirement already satisfied: requests>=2.25.0 in /Users/jhk/Library/Python/3.9/lib/python/site-packages (from spotipy) (2.31.0)
Requirement already satisfied: redis>=3.5.3 in /Users/jhk/Library/Python/3.9/lib/python/site-packages (from spotipy) (5.0.1)
Requirement already satisfied: urllib3>=1.26.0 in /Users/jhk/Library/Python/3.9/lib/python/site-packages (from spotipy) (2.1.0)
Requirement already satisfied: async-timeout>=4.0.2 in /Users/jhk/Library/Python/3.9/lib/python/site-packages (from redis>=3.5.3->spotipy) (4.0.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jhk/Library/Python/3.9/lib/python/site-packages (from requests>=2.25.0->spotipy) (2023.11.17)
Requirement already satisfied: idna<4,>=2.5 in /Users/jhk/Library/Python/3.9/lib/python/site-packages (from requests>=2.25.0->spotipy) (3.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/jhk/Library/Python/3.9/lib/python/site-packages (from requests>=2.25.0->spotipy) (3.3.2)
WARNING: You are using pip version 21.2.4; however, version 23.3.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [4]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import pandas as pd
import time

# Client ID set-up for API
client_id = 'd71f5ebb2095498d998db9f448b8b2b1'
client_secret = '5dcc3dd468b64967991fcb2343bfef4d'

client_credentials_manager = SpotifyClientCredentials(client_id, client_secret)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

ModuleNotFoundError: No module named 'pandas'

In [ ]:
#example code: Dua Lipa
result = sp.search("Dua Lipa")
track = result['tracks']['items'][0]

artist = sp.artist(track["artists"][0]["external_urls"]["spotify"])
print("artist genres:", artist["genres"])

album = sp.album(track["album"]["external_urls"]["spotify"])
print("album genres:", album["genres"])
print("album release-date:", album["release_date"])

artist genres: ['dance pop', 'pop', 'uk pop']
album genres: []
album release-date: 2020-03-27

## Set Up 'get_genre' Function

In [ ]:
def get_genre(artist):
    result = sp.search(artist)
    track = result['tracks']['items'][0]
    artist = sp.artist(track["artists"][0]["external_urls"]["spotify"])
    
    genre = artist['genres']
    return genre

In [ ]:
get_genre('Dua Lipa')

Out[4]: ['dance pop', 'pop', 'uk pop']

## Load CSV and add Genre

In [ ]:
import pandas as pd
df = pd.read_csv('/Workspace/Users/carrie.oh@curinos.com/artists.csv')
df['artist_genre'] = str("")
df

,year,month,week,rank,track title,artist name,artist_genre
0,2021,11,1,1,NaN,Drake,
1,2021,11,1,2,NaN,Taylor Swift,
2,2021,11,1,3,NaN,Kanye West,
3,2021,11,1,4,NaN,Juice WRLD,
4,2021,11,1,5,NaN,Ed Sheeran,
...,...,...,...,...,...,...,...
4995,2023,11,1,196,NaN,System Of A Down,
4996,2023,11,1,197,NaN,Grupo Firme,
4997,2023,11,1,198,NaN,Justin Timberlake,
4998,2023,11,1,199,NaN,Foo Fighters,
4999,2023,11,1,200,NaN,Dominic Fike,

In [ ]:
#creating artist:genre dictionary for shorter runtime
artist_dict = {}
for i in df['artist name']:
    artist_dict[i] = ""
#artist_dict

In [ ]:
len(artist_dict.keys())

Out[7]: 394

In [ ]:
#pull genre using spotipy
for i in artist_dict.keys():
    artist_dict[i] = get_genre(i)
artist_dict

Out[25]: {'Drake': ['canadian hip hop', 'canadian pop', 'hip hop', 'pop rap', 'rap'],
 'Taylor Swift': ['pop'],
 'Kanye West': ['chicago rap', 'hip hop', 'rap'],
 'Juice WRLD': ['chicago rap', 'melodic rap', 'rap'],
 'Ed Sheeran': ['pop', 'singer-songwriter pop', 'uk pop'],
 'The Weeknd': ['canadian contemporary r&b', 'canadian pop', 'pop'],
 'Doja Cat': ['dance pop', 'pop'],
 'Bad Bunny': ['reggaeton', 'trap latino', 'urbano latino'],
 'Polo G': ['chicago rap', 'rap'],
 'Lil Baby': ['atl hip hop', 'atl trap', 'rap', 'trap'],
 'Justin Bieber': ['canadian pop', 'pop'],
 'Lil Uzi Vert': ['hip hop', 'melodic rap', 'philly rap', 'rage rap', 'rap'],
 'J. Cole': ['conscious hip hop', 'hip hop', 'north carolina hip hop', 'rap'],
 'Billie Eilish': ['indie hip hop'],
 'Travis Scott': ['hip hop', 'rap', 'slap house'],
 'YoungBoy Never Broke Again': ['baton rouge rap', 'rap'],
 'Ariana Grande': ['pop'],
 'Young Thug': ['atl hip hop',
  'atl trap',
  'gangster rap',
  'melodic rap',
  'rap',
  'trap'],
 'Adele': ['british soul', 'pop', 'pop soul', 'uk pop'],
 'Future': ['atl hip hop', 'hip hop', 'rap', 'southern hip hop', 'trap'],
 'Eminem': ['detroit hip hop', 'hip hop', 'rap'],
 '$uicideboy$': ['cloud rap',
  'dark trap',
  'new orleans rap',
  'underground hip hop'],
 '21 Savage': ['atl hip hop', 'hip hop', 'rap'],
 'Mac Miller': ['hip hop', 'pittsburgh rap', 'pop rap', 'rap'],
 'Morgan Wallen': ['contemporary country'],
 'XXXTENTACION': ['emo rap', 'miami hip hop'],
 'Post Malone': ['dfw rap', 'melodic rap', 'pop', 'rap'],
 'Lil Durk': ['chicago drill',
  'chicago rap',
  'drill',
  'hip hop',
  'rap',
  'trap'],
 'Kendrick Lamar': ['conscious hip hop', 'hip hop', 'rap', 'west coast rap'],
 'Lil Nas X': ['lgbtq+ hip hop'],
 'Megan Thee Stallion': ['houston rap', 'pop', 'r&b', 'rap', 'trap queen'],
 'Trippie Redd': ['melodic rap', 'rap', 'trap'],
 'Playboi Carti': ['atl hip hop', 'plugg', 'pluggnb', 'rage rap', 'rap'],
 'Olivia Rodrigo': ['pop'],
 'Tyler, The Creator': ['hip hop', 'rap'],
 'A$AP Rocky': ['east coast hip hop', 'hip hop', 'rap', 'trap'],
 'BTS': ['k-pop', 'k-pop boy group', 'pop'],
 'The Kid LAROI': ['australian hip hop'],
 'Lil Wayne': ['hip hop', 'new orleans rap', 'pop rap', 'rap', 'trap'],
 'Jack Harlow': ['deep underground hip hop',
  'kentucky hip hop',
  'pop rap',
  'rap'],
 'Gunna': ['atl hip hop', 'melodic rap', 'rap', 'trap'],
 'DaBaby': ['hip hop', 'north carolina hip hop', 'pop rap', 'rap', 'trap'],
 'Pop Smoke': ['brooklyn drill', 'rap'],
 'J Balvin': ['reggaeton',
  'reggaeton colombiano',
  'trap latino',
  'urbano latino'],
 'Khalid': ['pop', 'pop r&b'],
 'Rihanna': ['barbadian pop', 'pop', 'urban contemporary'],
 'Dua Lipa': ['dance pop', 'pop', 'uk pop'],
 'Luke Combs': ['contemporary country', 'country'],
 'Lil Peep': ['cloud rap', 'emo rap', 'lgbtq+ hip hop'],
 'Bruno Mars': ['dance pop', 'pop'],
 'Kid Cudi': ['hip hop', 'ohio hip hop', 'pop rap', 'rap'],
 'Coldplay': ['permanent wave', 'pop'],
 'SZA': ['pop', 'r&b', 'rap'],
 'Chris Brown': ['r&b', 'rap'],
 'Machine Gun Kelly': ['ohio hip hop', 'pop rap'],
 'Nicki Minaj': ['hip pop', 'pop', 'queens hip hop', 'rap'],
 'Lana Del Rey': ['art pop', 'pop'],
 'Lil Tjay': ['brooklyn drill', 'melodic rap', 'nyc rap', 'rap'],
 'Halsey': ['electropop', 'etherpop', 'indie poptimism', 'pop'],
 'Don Toliver': ['pop rap', 'rap', 'trap'],
 'Baby Keem': ['hip hop', 'rap'],
 'Michael Jackson': ['r&b', 'soul'],
 'Harry Styles': ['pop'],
 'Rauw Alejandro': ['puerto rican pop',
  'reggaeton',
  'trap latino',
  'urbano latino'],
 'Lil Tecca': ['melodic rap', 'pluggnb', 'rap'],
 'Imagine Dragons': ['modern rock', 'pop', 'rock'],
 'Marshmello': ['brostep', 'edm', 'pop', 'progressive electro house'],
 'Frank Ocean': ['lgbtq+ hip hop', 'neo soul'],
 'A Boogie Wit da Hoodie': ['melodic rap', 'rap', 'trap'],
 'NF': ['hip hop', 'pop rap'],
 'The Beatles': ['british invasion',
  'classic rock',
  'merseybeat',
  'psychedelic rock',
  'rock'],
 'Metro Boomin': ['rap'],
 'Glass Animals': ['gauze pop',
  'indietronica',
  'modern rock',
  'pov: indie',
  'shiver pop'],
 'Big Sean': ['detroit hip hop', 'hip hop', 'pop rap', 'r&b', 'rap', 'trap'],
 'Kodak Black': ['florida drill',
  'florida rap',
  'melodic rap',
  'miami hip hop',
  'rap',
  'trap',
  'trap latino'],
 'Maroon 5': ['pop'],
 'Moneybagg Yo': ['memphis hip hop',
  'rap',
  'southern hip hop',
  'tennessee hip hop',
  'trap'],
 'Rod Wave': ['florida rap'],
 'blackbear': ['pop'],
 'Meek Mill': ['hip hop',
  'philly rap',
  'pop rap',
  'rap',
  'southern hip hop',
  'trap'],
 'The Neighbourhood': ['modern alternative rock',
  'modern rock',
  'pop',
  'pov: indie'],
 'Eslabon Armado': ['corrido',
  'corridos tumbados',
  'sad sierreno',
  'sierreno'],
 'Ty Dolla $ign': ['hip hop',
  'pittsburgh rap',
  'pop rap',
  'rap',
  'southern hip hop',
  'trap'],
 'Elton John': ['glam rock', 'mellow gold', 'piano rock', 'rock'],
 'Sleepy Hallow': ['brooklyn drill', 'nyc rap'],
 'Migos': ['atl hip hop', 'hip hop', 'pop rap', 'rap', 'trap'],
 'One Direction': ['boy band', 'pop', 'post-teen pop', 'talent show'],
 'WILLOW': ['afrofuturism', 'pop', 'post-teen pop', 'pov: indie'],
 'Lady Gaga': ['corridos tumbados', 'sad sierreno'],
 'Cardi B': ['pop', 'rap'],
 'Ozuna': ['puerto rican pop', 'reggaeton', 'trap latino', 'urbano latino'],
 'Beyoncé': ['pop', 'r&b'],
 'JAY-Z': ['east coast hip hop', 'gangster rap', 'hip hop', 'pop rap', 'rap'],
 'Joji': ['viral pop'],
 'Katy Perry': ['pop'],
 'Roddy Ricch': ['melodic rap', 'rap', 'trap'],
 'Twenty One Pilots': ['modern rock', 'pop', 'pov: indie', 'rock'],
 'Lin-Manuel Miranda': ['broadway', 'show tunes'],
 'Giveon': ['r&b'],
 'Farruko': ['reggaeton', 'trap latino', 'urbano latino'],
 'Panic! At The Disco': ['modern rock', 'pop'],
 'Anuel AA': ['reggaeton',
  'reggaeton flow',
  'trap boricua',
  'trap latino',
  'urbano latino'],
 'Jason Aldean': ['contemporary country',
  'country',
  'country road',
  'modern country rock'],
 'Miley Cyrus': ['pop'],
 'Grupo Firme': ['musica mexicana', 'norteno', 'sierreno'],
 'Queen': ['k-pop girl group'],
 'Kevin Gates': ['baton rouge rap', 'rap', 'southern hip hop', 'trap'],
 'Mitski': ['brooklyn indie', 'pov: indie'],
 'Kane Brown': ['black americana',
  'contemporary country',
  'country',
  'country road'],
 'Wiz Khalifa': ['hip hop',
  'pittsburgh rap',
  'pop rap',
  'rap',
  'southern hip hop',
  'trap'],
 'Ski Mask The Slump God': ['hip hop',
  'miami hip hop',
  'pop rap',
  'rap',
  'trap'],
 'Linkin Park': ['alternative metal',
  'nu metal',
  'post-grunge',
  'rap metal',
  'rock'],
 'Fall Out Boy': ['emo', 'modern rock', 'pop', 'rock'],
 'Melanie Martinez': ['alt z', 'electropop', 'pop'],
 'Chris Stapleton': ['contemporary country', 'outlaw country'],
 'KAROL G': ['reggaeton',
  'reggaeton colombiano',
  'trap latino',
  'urbano latino'],
 'Sam Smith': ['pop', 'uk pop'],
 'Hozier': ['irish singer-songwriter', 'modern rock', 'pov: indie'],
 'Florida Georgia Line': ['contemporary country',
  'country',
  'country pop',
  'country road',
  'modern country rock'],
 'Nirvana': ['grunge', 'permanent wave', 'rock'],
 'Jhayco': ['reggaeton', 'trap latino', 'urbano latino'],
 'Brent Faiyaz': ['r&b', 'rap'],
 'Shawn Mendes': ['canadian pop', 'pop', 'viral pop'],
 'Fleetwood Mac': ['album rock',
  'classic rock',
  'rock',
  'soft rock',
  'yacht rock'],
 'Russ': [],
 'Conan Gray': ['bedroom pop', 'pop', 'pov: indie'],
 'Arctic Monkeys': ['garage rock',
  'modern rock',
  'permanent wave',
  'rock',
  'sheffield indie'],
 'Logic': ['conscious hip hop', 'hip hop', 'pop rap', 'rap'],
 'YNW Melly': ['melodic rap', 'rap'],
 'Myke Towers': ['reggaeton', 'trap latino', 'urbano latino'],
 'Daddy Yankee': ['latin hip hop',
  'reggaeton',
  'trap latino',
  'urbano latino'],
 'David Guetta': ['big room', 'dance pop', 'edm', 'pop', 'pop dance'],
 'G Herbo': ['chicago drill', 'chicago rap', 'drill', 'trap'],
 'Childish Gambino': ['atl hip hop', 'hip hop', 'rap'],
 'AC/DC': ['australian rock', 'hard rock', 'rock'],
 'Joyner Lucas': ['boston hip hop', 'hip hop', 'pop rap', 'rap'],
 'John Mayer': ['neo mellow', 'singer-songwriter'],
 'iann dior': ['melodic rap'],
 'Metallica': ['hard rock',
  'metal',
  'old school thrash',
  'rock',
  'thrash metal'],
 'Tame Impala': ['australian psych', 'modern rock', 'neo-psychedelic', 'rock'],
 'Cody Johnson': ['classic texas country', 'contemporary country'],
 'Key Glock': ['memphis hip hop',
  'rap',
  'southern hip hop',
  'tennessee hip hop',
  'trap'],
 'Kali Uchis': ['colombian pop'],
 'King Von': ['chicago rap'],
 'Red Hot Chili Peppers': ['alternative rock',
  'funk metal',
  'funk rock',
  'permanent wave',
  'rock'],
 'Tyler Childers': ['kentucky indie', 'kentucky roots', 'outlaw country'],
 'My Chemical Romance': ['emo',
  'modern rock',
  'pop punk',
  'pov: indie',
  'rock'],
 'Green Day': ['modern rock', 'permanent wave', 'punk', 'rock'],
 'Gorillaz': ['alternative hip hop', 'modern rock', 'rock'],
 'Gucci Mane': ['atl hip hop',
  'dirty south rap',
  'hip hop',
  'pop rap',
  'rap',
  'southern hip hop',
  'trap'],
 'Luke Bryan': ['contemporary country',
  'country',
  'country road',
  'modern country rock'],
 'Camila Cabello': ['dance pop', 'pop'],
 'Summer Walker': ['r&b', 'rap'],
 'Frank Sinatra': ['adult standards', 'easy listening', 'lounge'],
 'Tory Lanez': ['canadian hip hop',
  'canadian trap',
  'melodic rap',
  'pop rap',
  'r&b',
  'rap',
  'trap'],
 'Jhené Aiko': ['r&b'],
 'Pitbull': ['dance pop', 'miami hip hop', 'pop'],
 'Selena Gomez': ['pop', 'post-teen pop'],
 'Tyga': ['hip hop', 'pop rap', 'rap', 'trap'],
 'Mariah Carey': ['dance pop', 'pop', 'urban contemporary'],
 'G-Eazy': ['indie pop rap', 'oakland hip hop', 'pop rap', 'rap'],
 'Clairo': ['bedroom pop', 'indie pop', 'pov: indie'],
 'Paramore': ['candy pop',
  'modern rock',
  'pixie',
  'pop',
  'pop emo',
  'pop punk',
  'rock'],
 'Britney Spears': ['dance pop', 'pop'],
 'Bryson Tiller': ['kentucky hip hop', 'r&b', 'rap'],
 'Mac DeMarco': ['edmonton indie', 'lo-fi indie', 'pov: indie'],
 'AJR': ['pov: indie'],
 'Maluma': ['latin pop',
  'reggaeton',
  'reggaeton colombiano',
  'trap latino',
  'urbano latino'],
 '6LACK': ['atl hip hop', 'melodic rap', 'r&b', 'rap', 'trap'],
 'Thomas Rhett': ['contemporary country',
  'country',
  'country road',
  'modern country rock'],
 'Bo Burnham': ['comic', 'pov: indie'],
 'USHER': ['atl hip hop',
  'contemporary r&b',
  'dance pop',
  'pop',
  'r&b',
  'rap',
  'south carolina hip hop',
  'urban contemporary'],
 'Lorde': ['art pop', 'metropopolis', 'nz pop', 'pop'],
 'Calvin Harris': ['dance pop',
  'edm',
  'electro house',
  'house',
  'pop',
  'pop dance',
  'progressive house',
  'uk dance'],
 'DJ Khaled': ['hip hop', 'miami hip hop', 'pop rap', 'rap'],
 '2Pac': ['g funk', 'gangster rap', 'hip hop', 'rap', 'west coast rap'],
 'Kacey Musgraves': ['classic texas country',
  'contemporary country',
  'country dawn'],
 'The Rolling Stones': ['album rock',
  'british invasion',
  'classic rock',
  'rock'],
 'Dan + Shay': ['contemporary country', 'country', 'country road'],
 'Diplo': ['dance pop', 'edm', 'electro house', 'moombahton', 'pop dance'],
 'Daniel Caesar': ['canadian contemporary r&b'],
 'Demi Lovato': ['pop', 'post-teen pop'],
 'Kehlani': ['pop', 'r&b', 'rap'],
 'NLE Choppa': ['memphis hip hop', 'rap'],
 '$NOT': ['aesthetic rap', 'cloud rap', 'florida rap', 'underground hip hop'],
 'Junior H': ['corrido',
  'corridos tumbados',
  'musica mexicana',
  'sad sierreno',
  'sierreno'],
 'Tainy': ['pop reggaeton', 'reggaeton', 'trap latino', 'urbano latino'],
 'H.E.R.': ['r&b', 'rap'],
 'Rex Orange County': ['bedroom pop'],
 'Slipknot': ['alternative metal', 'nu metal', 'rap metal', 'rock'],
 'Cavetown': ['bedroom pop', 'indie pop', 'pov: indie'],
 'The Lumineers': ['folk-pop', 'modern rock', 'stomp and holler'],
 'George Strait': ['contemporary country', 'country', 'country road'],
 'Led Zeppelin': ['album rock', 'classic rock', 'hard rock', 'rock'],
 'Lil Yachty': ['atl hip hop', 'melodic rap', 'rap', 'trap'],
 'Steve Lacy': ['afrofuturism'],
 'The Chainsmokers': ['pop'],
 'Sech': ['panamanian pop', 'reggaeton', 'trap latino', 'urbano latino'],
 'Swae Lee': ['dfw rap', 'melodic rap', 'pop', 'rap'],
 'Phoebe Bridgers': ['indie pop', 'la indie', 'pov: indie'],
 'Bing Crosby': ['adult standards', 'easy listening', 'lounge'],
 'Michael Bublé': ['adult standards', 'canadian pop', 'jazz pop', 'lounge'],
 'Pentatonix': ['a cappella', 'viral pop'],
 'Anderson .Paak': ['escape room', 'hip hop', 'indie soul', 'neo soul'],
 'Young Dolph': ['memphis hip hop',
  'rap',
  'southern hip hop',
  'tennessee hip hop',
  'trap'],
 'Silk Sonic': ['dance pop', 'pop'],
 'Nat King Cole': ['adult standards', 'lounge', 'soul', 'swing', 'vocal jazz'],
 'Kelly Clarkson': ['dance pop', 'pop', 'talent show'],
 'Andy Williams': ['adult standards', 'easy listening'],
 'Dean Martin': ['adult standards', 'easy listening', 'lounge', 'vocal jazz'],
 'Elvis Presley': ['rock-and-roll', 'rockabilly'],
 'Vince Guaraldi Trio': ['jazz trio'],
 'Arcane': ['dutch pop'],
 'Sia': ['australian dance', 'australian pop', 'pop'],
 'League of Legends': ['speedrun', 'video game music'],
 'Perry Como': ['adult standards', 'easy listening', 'lounge'],
 'GAYLE': ['modern alternative pop'],
 'John Legend': ['neo soul', 'pop', 'pop soul', 'urban contemporary'],
 'TWICE': ['k-pop', 'k-pop girl group', 'pop'],
 'Tate McRae': ['alt z', 'pop'],
 'Carrie Underwood': ['classic oklahoma country',
  'contemporary country',
  'country',
  'country dawn',
  'country road',
  'dance pop',
  'pop'],
 'Burl Ives': ['adult standards', 'american folk revival', 'lounge'],
 'Stephanie Beatriz': ['hollywood', 'movie tunes'],
 'Encanto - Cast': ['movie tunes'],
 'Diane Guerrero': ['movie tunes'],
 'Adassa': ['christian a cappella', 'college a cappella', 'lds', 'lds youth'],
 'OneRepublic': ['piano rock', 'pop'],
 'Chief Keef': ['chicago bop',
  'chicago drill',
  'chicago rap',
  'drill',
  'hip hop',
  'rap',
  'southern hip hop',
  'trap'],
 'Carolina Gaitán - La Gaita': ['movie tunes'],
 'Mauro Castillo': ['movie tunes'],
 'Chase Atlantic': ['alternative r&b'],
 'JID': ['hip hop', 'pop rap', 'rap', 'underground hip hop'],
 'Tiësto': ['big room',
  'brostep',
  'dutch edm',
  'edm',
  'house',
  'pop dance',
  'slap house',
  'trance'],
 'Labrinth': ['indie poptimism', 'pop'],
 'Yeat': ['canadian hip hop', 'canadian pop', 'hip hop', 'pop rap', 'rap'],
 'Mother Mother': ['pov: indie', 'vancouver indie'],
 'Sebastian Yatra': ['colombian pop',
  'latin pop',
  'reggaeton',
  'reggaeton colombiano',
  'trap latino',
  'urbano latino'],
 'PARTYNEXTDOOR': ['r&b', 'rap', 'urban contemporary'],
 'girl in red': ['bedroom pop', 'indie pop', 'norwegian indie', 'pov: indie'],
 'The Notorious B.I.G.': ['east coast hip hop',
  'gangster rap',
  'hardcore hip hop',
  'hip hop',
  'rap'],
 'Charlie Puth': ['pop', 'viral pop'],
 'Rick Ross': ['dirty south rap',
  'gangster rap',
  'hip hop',
  'rap',
  'southern hip hop',
  'trap'],
 'Zach Bryan': ['classic oklahoma country', 'modern country pop'],
 'Dr. Dre': ['g funk', 'gangster rap', 'hip hop', 'rap', 'west coast rap'],
 'Avril Lavigne': ['canadian pop', 'candy pop', 'dance pop', 'pop'],
 'Snoop Dogg': ['g funk',
  'gangster rap',
  'hip hop',
  'pop rap',
  'rap',
  'west coast rap'],
 '50 Cent': ['east coast hip hop',
  'gangster rap',
  'hip hop',
  'pop rap',
  'queens hip hop',
  'rap'],
 'Dominic Fike': ['alternative pop rock', 'pov: indie'],
 '5 Seconds of Summer': ['boy band', 'pop'],
 'Christian Nodal': ['mariachi', 'musica mexicana', 'ranchera'],
 'Kygo': ['edm', 'pop', 'pop dance', 'tropical house'],
 'Alicia Keys': ['neo soul', 'pop', 'r&b'],
 'Dreamville': ['hip hop', 'pop rap', 'rap'],
 'Foo Fighters': ['alternative metal',
  'alternative rock',
  'modern rock',
  'permanent wave',
  'post-grunge',
  'rock'],
 'Denzel Curry': ['dark trap',
  'drill',
  'hip hop',
  'miami hip hop',
  'pop rap',
  'rap',
  'trap',
  'underground hip hop'],
 'Pharrell Williams': ['dance pop', 'pop'],
 'Maren Morris': ['classic texas country', 'contemporary country'],
 'Mora': ['alt z'],
 '42 Dugg': ['detroit trap', 'southern hip hop', 'trap'],
 'Miranda Lambert': ['contemporary country',
  'country',
  'country dawn',
  'country road'],
 'Billy Joel': ['album rock',
  'classic rock',
  'heartland rock',
  'mellow gold',
  'piano rock',
  'rock',
  'singer-songwriter',
  'soft rock'],
 '2 Chainz': ['atl hip hop',
  'hip hop',
  'pop rap',
  'rap',
  'southern hip hop',
  'trap'],
 'Kenny Chesney': ['contemporary country', 'country', 'country road'],
 'Lizzo': ['escape room', 'minnesota hip hop', 'pop', 'trap queen'],
 'Pusha T': ['gangster rap',
  'hip hop',
  'pop rap',
  'rap',
  'southern hip hop',
  'trap',
  'virginia hip hop'],
 'Tems': ['afro r&b', 'alte', 'nigerian pop'],
 'Pooh Shiesty': [],
 'EST Gee': ['kentucky hip hop', 'memphis hip hop', 'southern hip hop'],
 'Luis R Conriquez': ['corrido',
  'corridos tumbados',
  'norteno',
  'sad sierreno',
  'sierreno'],
 'Becky G': ['latin pop',
  'latin viral pop',
  'rap latina',
  'reggaeton',
  'trap latino',
  'urbano latino'],
 'Zac Brown Band': ['contemporary country',
  'country',
  'country road',
  'modern country rock'],
 'Kate Bush': ['art pop',
  'art rock',
  'baroque pop',
  'new wave pop',
  'permanent wave',
  'piano rock',
  'singer-songwriter'],
 'Chencho Corleone': ['reggaeton',
  'reggaeton flow',
  'trap latino',
  'urbano latino'],
 'Blxst': ['pop rap', 'westcoast flow'],
 'BoyWithUke': ['sad rap'],
 'Eric Church': ['contemporary country',
  'country',
  'country road',
  'modern country rock'],
 'Lee Brice': ['contemporary country',
  'country',
  'country road',
  'modern country rock'],
 'Sam Hunt': ['contemporary country',
  'country',
  'country pop',
  'modern country rock'],
 'Tim McGraw': ['pop'],
 'Eagles': ['album rock',
  'classic rock',
  'heartland rock',
  'mellow gold',
  'rock',
  'soft rock',
  'yacht rock'],
 'Weezer': ['alternative rock',
  'modern power pop',
  'modern rock',
  'permanent wave',
  'rock'],
 'Journey': ['album rock',
  'classic rock',
  'hard rock',
  'heartland rock',
  'mellow gold',
  'rock',
  'soft rock'],
 'Yung Gravy': ['meme rap', 'minnesota hip hop'],
 'Shakira': ['colombian pop', 'dance pop', 'latin pop', 'pop'],
 'Jon Pardi': ['contemporary country',
  'country',
  'country road',
  'modern country rock'],
 'Creedence Clearwater Revival': ['classic rock',
  'country rock',
  'rock',
  'southern rock',
  'swamp rock'],
 'Cigarettes After Sex': ['ambient pop',
  'dream pop',
  'el paso indie',
  'shoegaze'],
 'Toby Keith': ['classic oklahoma country',
  'contemporary country',
  'country',
  'country road'],
 'ABBA': ['europop', 'swedish pop'],
 'Deftones': ['alternative metal',
  'nu metal',
  'rap metal',
  'rock',
  'sacramento indie'],
 'Shinedown': ['alternative metal', 'nu metal', 'post-grunge'],
 'Bob Marley & The Wailers': ['reggae', 'roots reggae'],
 'NAV': ['canadian hip hop', 'canadian trap', 'melodic rap', 'rap', 'trap'],
 'Dance Gavin Dance': ['pixie', 'sacramento indie', 'screamo', 'swancore'],
 'Nardo Wick': ['florida drill', 'florida rap', 'southern hip hop'],
 'Maggie Rogers': ['indie pop'],
 'Fuerza Regida': ['corrido', 'corridos tumbados', 'sad sierreno', 'sierreno'],
 'Joey Bada$$': ['conscious hip hop', 'hip hop', 'rap'],
 'Justin Timberlake': ['dance pop', 'pop'],
 'Carin Leon': ['corrido', 'musica mexicana', 'sad sierreno', 'sierreno'],
 'Offset': ['atl hip hop', 'hip hop', 'pop rap', 'rap', 'trap'],
 'Ivan Cornejo': ['sad sierreno'],
 'Bailey Zimmerman': ['contemporary country', 'modern country pop'],
 'BLACKPINK': ['k-pop', 'k-pop girl group', 'pop'],
 'Five Finger Death Punch': ['alternative metal', 'groove metal', 'nu metal'],
 'Quavo': ['atl hip hop', 'melodic rap', 'rap', 'trap'],
 'Pierce The Veil': ['pop punk', 'screamo'],
 'ROSALÍA': ['rap latina', 'trap dominicano'],

In [ ]:
#add genre to df
for i in range(len(df)):
    df['artist_genre'].iloc[i] = artist_dict[df['artist name'].iloc[i]]

/databricks/python/lib/python3.9/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [ ]:
display(df)

year,month,week,rank,track title,artist name,artist_genre
2021,11,1,1,null,Drake,"List(canadian hip hop, canadian pop, hip hop, pop rap, rap)"
2021,11,1,2,null,Taylor Swift,List(pop)
2021,11,1,3,null,Kanye West,"List(chicago rap, hip hop, rap)"
2021,11,1,4,null,Juice WRLD,"List(chicago rap, melodic rap, rap)"
2021,11,1,5,null,Ed Sheeran,"List(pop, singer-songwriter pop, uk pop)"
2021,11,1,6,null,The Weeknd,"List(canadian contemporary r&b, canadian pop, pop)"
2021,11,1,7,null,Doja Cat,"List(dance pop, pop)"
2021,11,1,8,null,Bad Bunny,"List(reggaeton, trap latino, urbano latino)"
2021,11,1,9,null,Polo G,"List(chicago rap, rap)"
2021,11,1,10,null,Lil Baby,"List(atl hip hop, atl trap, rap, trap)"
2021,11,1,11,null,Justin Bieber,"List(canadian pop, pop)"
2021,11,1,12,null,Lil Uzi Vert,"List(hip hop, melodic rap, philly rap, rage rap, rap)"
2021,11,1,13,null,J. Cole,"List(conscious hip hop, hip hop, north carolina hip hop, rap)"
2021,11,1,14,null,Billie Eilish,List(indie hip hop)
2021,11,1,15,null,Travis Scott,"List(hip hop, rap, slap house)"
2021,11,1,16,null,YoungBoy Never Broke Again,"List(baton rouge rap, rap)"
2021,11,1,17,null,Ariana Grande,List(pop)
2021,11,1,18,null,Young Thug,"List(atl hip hop, atl trap, gangster rap, melodic rap, rap, trap)"
2021,11,1,19,null,Adele,"List(british soul, pop, pop soul, uk pop)"
2021,11,1,20,null,Future,"List(atl hip hop, hip hop, rap, southern hip hop, trap)"
2021,11,1,21,null,Eminem,"List(detroit hip hop, hip hop, rap)"
2021,11,1,22,null,$uicideboy$,"List(cloud rap, dark trap, new orleans rap, underground hip hop)"
2021,11,1,23,null,21 Savage,"List(atl hip hop, hip hop, rap)"
2021,11,1,24,null,Mac Miller,"List(hip hop, pittsburgh rap, pop rap, rap)"
2021,11,1,25,null,Morgan Wallen,List(contemporary country)
2021,11,1,26,null,XXXTENTACION,"List(emo rap, miami hip hop)"
2021,11,1,27,null,Post Malone,"List(dfw rap, melodic rap, pop, rap)"
2021,11,1,28,null,Lil Durk,"List(chicago drill, chicago rap, drill, hip hop, rap, trap)"
2021,11,1,29,null,Kendrick Lamar,"List(conscious hip hop, hip hop, rap, west coast rap)"
2021,11,1,30,null,Lil Nas X,List(lgbtq+ hip hop)
2021,11,1,31,null,Megan Thee Stallion,"List(houston rap, pop, r&b, rap, trap queen)"
2021,11,1,32,null,Trippie Redd,"List(melodic rap, rap, trap)"
2021,11,1,33,null,Playboi Carti,"List(atl hip hop, plugg, pluggnb, rage rap, rap)"
2021,11,1,34,null,Olivia Rodrigo,List(pop)
2021,11,1,35,null,"Tyler, The Creator","List(hip hop, rap)"
2021,11,1,36,null,A$AP Rocky,"List(east coast hip hop, hip hop, rap, trap)"
2021,11,1,37,null,BTS,"List(k-pop, k-pop boy group, pop)"
2021,11,1,38,null,The Kid LAROI,List(australian hip hop)
2021,11,1,39,null,Lil Wayne,"List(hip hop, new orleans rap, pop rap, rap, trap)"
2021,11,1,40,null,Jack Harlow,"List(deep underground hip hop, kentucky hip hop, pop rap, rap)"
2021,11,1,41,null,Gunna,"List(atl hip hop, melodic rap, rap, trap)"
2021,11,1,42,null,DaBaby,"List(hip hop, north carolina hip hop, pop rap, rap, trap)"
2021,11,1,43,null,Pop Smoke,"List(brooklyn drill, rap)"
2021,11,1,44,null,J Balvin,"List(reggaeton, reggaeton colombiano, trap latino, urbano latino)"
2021,11,1,45,null,Khalid,"List(pop, pop r&b)"
2021,11,1,46,null,Rihanna,"List(barbadian pop, pop, urban contemporary)"
2021,11,1,47,null,Dua Lipa,"List(dance pop, pop, uk pop)"
2021,11,1,48,null,Luke Combs,"List(contemporary country, country)"
2021,11,1,49,null,Lil Peep,"List(cloud rap, emo rap, lgbtq+ hip hop)"
2021,11,1,50,null,Bruno Mars,"List(dance pop, pop)"
2021,11,1,51,null,Kid Cudi,"List(hip hop, ohio hip hop, pop rap, rap)"
2021,11,1,52,null,Coldplay,"List(permanent wave, pop)"
2021,11,1,53,null,SZA,"List(pop, r&b, rap)"
2021,11,1,54,null,Chris Brown,"List(r&b, rap)"
2021,11,1,55,null,Machine Gun Kelly,"List(ohio hip hop, pop rap)"
2021,11,1,56,null,Nicki Minaj,"List(hip pop, pop, queens hip hop, rap)"
2021,11,1,57,null,Lana Del Rey,"List(art pop, pop)"
2021,11,1,58,null,Lil Tjay,"List(brooklyn drill, melodic rap, nyc rap, rap)"
2021,11,1,59,null,Halsey,"List(electropop, etherpop, indie poptimism, pop)"
2021,11,1,60,null,Don Toliver,"List(pop rap, rap, trap)"
2021,11,1,61,null,Baby Keem,"List(hip hop, rap)"
2021,11,1,62,null,Michael Jackson,"List(r&b, soul)"
2021,11,1,63,null,Harry Styles,List(pop)
2021,11,1,64,null,Rauw Alejandro,"List(puerto rican pop, reggaeton, trap latino, urbano latino)"
2021,11,1,65,null,Lil Tecca,"List(melodic rap, pluggnb, rap)"
2021,11,1,66,null,Imagine Dragons,"List(modern rock, pop, rock)"
2021,11,1,67,null,Marshmello,"List(brostep, edm, pop, progressive electro house)"
2021,11,1,68,null,Frank Ocean,"List(lgbtq+ hip hop, neo soul)"
2021,11,1,69,null,A Boogie Wit da Hoodie,"List(melodic rap, rap, trap)"
2021,11,1,70,null,NF,"List(hip hop, pop rap)"
2021,11,1,71,null,The Beatles,"List(british invasion, classic rock, merseybeat, psychedelic rock, rock)"
2021,11,1,72,null,Metro Boomin,List(rap)
2021,11,1,73,null,Glass Animals,"List(gauze pop, indietronica, modern rock, pov: indie, shiver pop)"
2021,11,1,74,null,Big Sean,"List(detroit hip hop, hip hop, pop rap, r&b, rap, trap)"
2021,11,1,75,null,Kodak Black,"List(florida drill, florida rap, melodic rap, miami hip hop, rap, trap, trap latino)"
2021,11,1,76,null,Maroon 5,List(pop)
2021,11,1,77,null,Moneybagg Yo,"List(memphis hip hop, rap, southern hip hop, tennessee hip hop, trap)"
2021,11,1,78,null,Rod Wave,List(florida rap)
2021,11,1,79,null,blackbear,List(pop)
2021,11,1,80,null,Meek Mill,"List(hip hop, philly rap, pop rap, rap, southern hip hop, trap)"
2021,11,1,81,null,The Neighbourhood,"List(modern alternative rock, modern rock, pop, pov: indie)"
2021,11,1,82,null,Eslabon Armado,"List(corrido, corridos tumbados, sad sierreno, sierreno)"
2021,11,1,83,null,Ty Dolla $ign,"List(hip hop, pittsburgh rap, pop rap, rap, southern hip hop, trap)"
2021,11,1,84,null,Elton John,"List(glam rock, mellow gold, piano rock, rock)"
2021,11,1,85,null,Sleepy Hallow,"List(brooklyn drill, nyc rap)"
2021,11,1,86,null,Migos,"List(atl hip hop, hip hop, pop rap, rap, trap)"
2021,11,1,87,null,One Direction,"List(boy band, pop, post-teen pop, talent show)"
2021,11,1,88,null,WILLOW,"List(afrofuturism, pop, post-teen pop, pov: indie)"
2021,11,1,89,null,Lady Gaga,"List(corridos tumbados, sad sierreno)"
2021,11,1,90,null,Cardi B,"List(pop, rap)"
2021,11,1,91,null,Ozuna,"List(puerto rican pop, reggaeton, trap latino, urbano latino)"
2021,11,1,92,null,Beyoncé,"List(pop, r&b)"
2021,11,1,93,null,JAY-Z,"List(east coast hip hop, gangster rap, hip hop, pop rap, rap)"
2021,11,1,94,null,Joji,List(viral pop)
2021,11,1,95,null,Katy Perry,List(pop)
2021,11,1,96,null,Roddy Ricch,"List(melodic rap, rap, trap)"
2021,11,1,97,null,Twenty One Pilots,"List(modern rock, pop, pov: indie, rock)"
2021,11,1,98,null,Lin-Manuel Miranda,"List(broadway, show tunes)"
2021,11,1,99,null,Giveon,List(r&b)
2021,11,1,100,null,Farruko,"List(reggaeton, trap latino, urbano latino)"
2021,11,1,101,null,Panic! At The Disco,"List(modern rock, pop)"
2021,11,1,102,null,Anuel AA,"List(reggaeton, reggaeton flow, trap boricua, trap latino, urbano latino)"
2021,11,1,103,null,Jason Aldean,"List(contemporary country, country, country road, modern country rock)"
2021,11,1,104,null,Miley Cyrus,List(pop)
2021,11,1,105,null,Grupo Firme,"List(musica mexicana, norteno, sierreno)"
2021,11,1,106,null,Queen,List(k-pop girl group)
2021,11,1,107,null,Kevin Gates,"List(baton rouge rap, rap, southern hip hop, trap)"
2021,11,1,108,null,Mitski,"List(brooklyn indie, pov: indie)"
2021,11,1,109,null,Kane Brown,"List(black americana, contemporary country, country, country road)"
2021,11,1,110,null,Wiz Khalifa,"List(hip hop, pittsburgh rap, pop rap, rap, southern hip hop, trap)"
2021,11,1,111,null,Ski Mask The Slump God,"List(hip hop, miami hip hop, pop rap, rap, trap)"
2021,11,1,112,null,Linkin Park,"List(alternative metal, nu metal, post-grunge, rap metal, rock)"
2021,11,1,113,null,Fall Out Boy,"List(emo, modern rock, pop, rock)"
2021,11,1,114,null,Melanie Martinez,"List(alt z, electropop, pop)"
2021,11,1,115,null,Chris Stapleton,"List(contemporary country, outlaw country)"
2021,11,1,116,null,KAROL G,"List(reggaeton, reggaeton colombiano, trap latino, urbano latino)"
2021,11,1,117,null,Sam Smith,"List(pop, uk pop)"
2021,11,1,118,null,Hozier,"List(irish singer-songwriter, modern rock, pov: indie)"
2021,11,1,119,null,Florida Georgia Line,"List(contemporary country, country, country pop, country road, modern country rock)"
2021,11,1,120,null,Nirvana,"List(grunge, permanent wave, rock)"
2021,11,1,121,null,Jhayco,"List(reggaeton, trap latino, urbano latino)"
2021,11,1,122,null,Brent Faiyaz,"List(r&b, rap)"
2021,11,1,123,null,Shawn Mendes,"List(canadian pop, pop, viral pop)"
2021,11,1,124,null,Fleetwood Mac,"List(album rock, classic rock, rock, soft rock, yacht rock)"
2021,11,1,125,null,Russ,List()
2021,11,1,126,null,Conan Gray,"List(bedroom pop, pop, pov: indie)"
2021,11,1,127,null,Arctic Monkeys,"List(garage rock, modern rock, permanent wave, rock, sheffield indie)"
2021,11,1,128,null,Logic,"List(conscious hip hop, hip hop, pop rap, rap)"
2021,11,1,129,null,YNW Melly,"List(melodic rap, rap)"
2021,11,1,130,null,Myke Towers,"List(reggaeton, trap latino, urbano latino)"
2021,11,1,131,null,Daddy Yankee,"List(latin hip hop, reggaeton, trap latino, urbano latino)"
2021,11,1,132,null,David Guetta,"List(big room, dance pop, edm, pop, pop dance)"
2021,11,1,133,null,G Herbo,"List(chicago drill, chicago rap, drill, trap)"
2021,11,1,134,null,Childish Gambino,"List(atl hip hop, hip hop, rap)"
2021,11,1,135,null,AC/DC,"List(australian rock, hard rock, rock)"
2021,11,1,136,null,Joyner Lucas,"List(boston hip hop, hip hop, pop rap, rap)"
2021,11,1,137,null,John Mayer,"List(neo mellow, singer-songwriter)"
2021,11,1,138,null,iann dior,List(melodic rap)
2021,11,1,139,null,Metallica,"List(hard rock, metal, old school thrash, rock, thrash metal)"
2021,11,1,140,null,Tame Impala,"List(australian psych, modern rock, neo-psychedelic, rock)"
2021,11,1,141,null,Cody Johnson,"List(classic texas country, contemporary country)"
2021,11,1,142,null,Key Glock,"List(memphis hip hop, rap, southern hip hop, tennessee hip hop, trap)"
2021,11,1,143,null,Kali Uchis,List(colombian pop)
2021,11,1,144,null,King Von,List(chicago rap)
2021,11,1,145,null,Red Hot Chili Peppers,"List(alternative rock, funk metal, funk rock, permanent wave, rock)"
2021,11,1,146,null,Tyler Childers,"List(kentucky indie, kentucky roots, outlaw country)"
2021,11,1,147,null,My Chemical Romance,"List(emo, modern rock, pop punk, pov: indie, rock)"
2021,11,1,148,null,Green Day,"List(modern rock, permanent wave, punk, rock)"
2021,11,1,149,null,Gorillaz,"List(alternative hip hop, modern rock, rock)"
2021,11,1,150,null,Gucci Mane,"List(atl hip hop, dirty south rap, hip hop, pop rap, rap, southern hip hop, trap)"
2021,11,1,151,null,Luke Bryan,"List(contemporary country, country, country road, modern country rock)"
2021,11,1,152,null,Camila Cabello,"List(dance pop, pop)"
2021,11,1,153,null,Summer Walker,"List(r&b, rap)"
2021,11,1,154,null,Frank Sinatra,"List(adult standards, easy listening, lounge)"
2021,11,1,155,null,Tory Lanez,"List(canadian hip hop, canadian trap, melodic rap, pop rap, r&b, rap, trap)"
2021,11,1,156,null,Jhené Aiko,List(r&b)
2021,11,1,157,null,Pitbull,"List(dance pop, miami hip hop, pop)"
2021,11,1,158,null,Selena Gomez,"List(pop, post-teen pop)"
2021,11,1,159,null,Tyga,"List(hip hop, pop rap, rap, trap)"
2021,11,1,160,null,Mariah Carey,"List(dance pop, pop, urban contemporary)"
2021,11,1,161,null,G-Eazy,"List(indie pop rap, oakland hip hop, pop rap, rap)"
2021,11,1,162,null,Clairo,"List(bedroom pop, indie pop, pov: indie)"
2021,11,1,163,null,Paramore,"List(candy pop, modern rock, pixie, pop, pop emo, pop punk, rock)"
2021,11,1,164,null,Britney Spears,"List(dance pop, pop)"
2021,11,1,165,null,Bryson Tiller,"List(kentucky hip hop, r&b, rap)"
2021,11,1,166,null,Mac DeMarco,"List(edmonton indie, lo-fi indie, pov: indie)"
2021,11,1,167,null,AJR,List(pov: indie)
2021,11,1,168,null,Maluma,"List(latin pop, reggaeton, reggaeton colombiano, trap latino, urbano latino)"
2021,11,1,169,null,6LACK,"List(atl hip hop, melodic rap, r&b, rap, trap)"
2021,11,1,170,null,Thomas Rhett,"List(contemporary country, country, country road, modern country rock)"
2021,11,1,171,null,Bo Burnham,"List(comic, pov: indie)"
2021,11,1,172,null,USHER,"List(atl hip hop, contemporary r&b, dance pop, pop, r&b, rap, south carolina hip hop, urban contemporary)"
2021,11,1,173,null,Lorde,"List(art pop, metropopolis, nz pop, pop)"
2021,11,1,174,null,Calvin Harris,"List(dance pop, edm, electro house, house, pop, pop dance, progressive house, uk dance)"
2021,11,1,175,null,DJ Khaled,"List(hip hop, miami hip hop, pop rap, rap)"
2021,11,1,176,null,2Pac,"List(g funk, gangster rap, hip hop, rap, west coast rap)"
2021,11,1,177,null,Kacey Musgraves,"List(classic texas country, contemporary country, country dawn)"
2021,11,1,178,null,The Rolling Stones,"List(album rock, british invasion, classic rock, rock)"
2021,11,1,179,null,Dan + Shay,"List(contemporary country, country, country road)"
2021,11,1,180,null,Diplo,"List(dance pop, edm, electro house, moombahton, pop dance)"
2021,11,1,181,null,Daniel Caesar,List(canadian contemporary r&b)
2021,11,1,182,null,Demi Lovato,"List(pop, post-teen pop)"
2021,11,1,183,null,Kehlani,"List(pop, r&b, rap)"
2021,11,1,184,null,NLE Choppa,"List(memphis hip hop, rap)"
2021,11,1,185,null,$NOT,"List(aesthetic rap, cloud rap, florida rap, underground hip hop)"
2021,11,1,186,null,Junior H,"List(corrido, corridos tumbados, musica mexicana, sad sierreno, sierreno)"
2021,11,1,187,null,Tainy,"List(pop reggaeton, reggaeton, trap latino, urbano latino)"
2021,11,1,188,null,H.E.R.,"List(r&b, rap)"
2021,11,1,189,null,Rex Orange County,List(bedroom pop)
2021,11,1,190,null,Slipknot,"List(alternative metal, nu metal, rap metal, rock)"
2021,11,1,191,null,Cavetown,"List(bedroom pop, indie pop, pov: indie)"
2021,11,1,192,null,The Lumineers,"List(folk-pop, modern rock, stomp and holler)"
2021,11,1,193,null,George Strait,"List(contemporary country, country, country road)"
2021,11,1,194,null,Led Zeppelin,"List(album rock, classic rock, hard rock, rock)"
2021,11,1,195,null,Lil Yachty,"List(atl hip hop, melodic rap, rap, trap)"
2021,11,1,196,null,Steve Lacy,List(afrofuturism)
2021,11,1,197,null,The Chainsmokers,List(pop)
2021,11,1,198,null,Sech,"List(panamanian pop, reggaeton, trap latino, urbano latino)"
2021,11,1,199,null,Swae Lee,"List(dfw rap, melodic rap, pop, rap)"
2021,11,1,200,null,Phoebe Bridgers,"List(indie pop, la indie, pov: indie)"
2021,12,1,1,null,Taylor Swift,List(pop)
2021,12,1,2,null,Drake,"List(canadian hip hop, canadian pop, hip hop, pop rap, rap)"
2021,12,1,3,null,Juice WRLD,"List(chicago rap, melodic rap, rap)"
2021,12,1,4,null,Kanye West,"List(chicago rap, hip hop, rap)"
2021,12,1,5,null,Adele,"List(british soul, pop, pop soul, uk pop)"
2021,12,1,6,null,The Weeknd,"List(canadian contemporary r&b, canadian pop, pop)"
2021,12,1,7,null,Doja Cat,"List(dance pop, pop)"
2021,12,1,8,null,Polo G,"List(chicago rap, rap)"
2021,12,1,9,null,Bad Bunny,"List(reggaeton, trap latino, urbano latino)"
2021,12,1,10,null,Ariana Grande,List(pop)
2021,12,1,11,null,Justin Bieber,"List(canadian pop, pop)"
2021,12,1,12,null,Lil Baby,"List(atl hip hop, atl trap, rap, trap)"
2021,12,1,13,null,Lil Uzi Vert,"List(hip hop, melodic rap, philly rap, rage rap, rap)"
2021,12,1,14,null,J. Cole,"List(conscious hip hop, hip hop, north carolina hip hop, rap)"
2021,12,1,15,null,Morgan Wallen,List(contemporary country)
2021,12,1,16,null,YoungBoy Never Broke Again,"List(baton rouge rap, rap)"
2021,12,1,17,null,Travis Scott,"List(hip hop, rap, slap house)"
2021,12,1,18,null,Post Malone,"List(dfw rap, melodic rap, pop, rap)"
2021,12,1,19,null,Bruno Mars,"List(dance pop, pop)"
2021,12,1,20,null,$uicideboy$,"List(cloud rap, dark trap, new orleans rap, underground hip hop)"
2021,12,1,21,null,Future,"List(atl hip hop, hip hop, rap, southern hip hop, trap)"
2021,12,1,22,null,Playboi Carti,"List(atl hip hop, plugg, pluggnb, rage rap, rap)"
2021,12,1,23,null,Billie Eilish,List(indie hip hop)
2021,12,1,24,null,BTS,"List(k-pop, k-pop boy group, pop)"
2021,12,1,25,null,XXXTENTACION,"List(emo rap, miami hip hop)"
2021,12,1,26,null,21 Savage,"List(atl hip hop, hip hop, rap)"
2021,12,1,27,null,Eminem,"List(detroit hip hop, hip hop, rap)"
2021,12,1,28,null,Kendrick Lamar,"List(conscious hip hop, hip hop, rap, west coast rap)"
2021,12,1,29,null,Ed Sheeran,"List(pop, singer-songwriter pop, uk pop)"
2021,12,1,30,null,Lil Durk,"List(chicago drill, chicago rap, drill, hip hop, rap, trap)"
2021,12,1,31,null,"Tyler, The Creator","List(hip hop, rap)"
2021,12,1,32,null,Mac Miller,"List(hip hop, pittsburgh rap, pop rap, rap)"
2021,12,1,33,null,Trippie Redd,"List(melodic rap, rap, trap)"
2021,12,1,34,null,Olivia Rodrigo,List(pop)
2021,12,1,35,null,The Beatles,"List(british invasion, classic rock, merseybeat, psychedelic rock, rock)"
2021,12,1,36,null,Young Thug,"List(atl hip hop, atl trap, gangster rap, melodic rap, rap, trap)"
2021,12,1,37,null,Bing Crosby,"List(adult standards, easy listening, lounge)"
2021,12,1,38,null,Michael Bublé,"List(adult standards, canadian pop, jazz pop, lounge)"
2021,12,1,39,null,Lil Nas X,List(lgbtq+ hip hop)
2021,12,1,40,null,Pentatonix,"List(a cappella, viral pop)"
2021,12,1,41,null,DaBaby,"List(hip hop, north carolina hip hop, pop rap, rap, trap)"
2021,12,1,42,null,The Kid LAROI,List(australian hip hop)
2021,12,1,43,null,Pop Smoke,"List(brooklyn drill, rap)"
2021,12,1,44,null,Gunna,"List(atl hip hop, melodic rap, rap, trap)"
2021,12,1,45,null,Luke Combs,"List(contemporary country, country)"
2021,12,1,46,null,Jack Harlow,"List(deep underground hip hop, kentucky hip hop, pop rap, rap)"
2021,12,1,47,null,Lil Wayne,"List(hip hop, new orleans rap, pop rap, rap, trap)"
2021,12,1,48,null,Frank Sinatra,"List(adult standards, easy listening, lounge)"
2021,12,1,49,null,Anderson .Paak,"List(escape room, hip hop, indie soul, neo soul)"
2021,12,1,50,null,SZA,"List(pop, r&b, rap)"
2021,12,1,51,null,Anuel AA,"List(reggaeton, reggaeton flow, trap boricua, trap latino, urbano latino)"
2021,12,1,52,null,Young Dolph,"List(memphis hip hop, rap, southern hip hop, tennessee hip hop, trap)"
2021,12,1,53,null,Khalid,"List(pop, pop r&b)"
2021,12,1,54,null,Rod Wave,List(florida rap)
2021,12,1,55,null,Megan Thee Stallion,"List(houston rap, pop, r&b, rap, trap queen)"
2021,12,1,56,null,Summer Walker,"List(r&b, rap)"
2021,12,1,57,null,J Balvin,"List(reggaeton, reggaeton colombiano, trap latino, urbano latino)"
2021,12,1,58,null,Lil Peep,"List(cloud rap, emo rap, lgbtq+ hip hop)"
2021,12,1,59,null,Mariah Carey,"List(dance pop, pop, urban contemporary)"
2021,12,1,60,null,Dua Lipa,"List(dance pop, pop, uk pop)"
2021,12,1,61,null,Kid Cudi,"List(hip hop, ohio hip hop, pop rap, rap)"
2021,12,1,62,null,Imagine Dragons,"List(modern rock, pop, rock)"
2021,12,1,63,null,Baby Keem,"List(hip hop, rap)"
2021,12,1,64,null,Kodak Black,"List(florida drill, florida rap, melodic rap, miami hip hop, rap, trap, trap latino)"
2021,12,1,65,null,Rihanna,"List(barbadian pop, pop, urban contemporary)"
2021,12,1,66,null,Machine Gun Kelly,"List(ohio hip hop, pop rap)"
2021,12,1,67,null,Silk Sonic,"List(dance pop, pop)"
2021,12,1,68,null,Harry Styles,List(pop)
2021,12,1,69,null,Chris Brown,"List(r&b, rap)"
2021,12,1,70,null,Lil Tjay,"List(brooklyn drill, melodic rap, nyc rap, rap)"
2021,12,1,71,null,Nicki Minaj,"List(hip pop, pop, queens hip hop, rap)"
2021,12,1,72,null,Coldplay,"List(permanent wave, pop)"
2021,12,1,73,null,Halsey,"List(electropop, etherpop, indie poptimism, pop)"
2021,12,1,74,null,Frank Ocean,"List(lgbtq+ hip hop, neo soul)"
2021,12,1,75,null,NF,"List(hip hop, pop rap)"
2021,12,1,76,null,Lin-Manuel Miranda,"List(broadway, show tunes)"
2021,12,1,77,null,Nat King Cole,"List(adult standards, lounge, soul, swing, vocal jazz)"
2021,12,1,78,null,A Boogie Wit da Hoodie,"List(melodic rap, rap, trap)"

In [ ]:
from datetime import date

today = date.today()

In [ ]:
df.to_csv(f'{today} artists_w_genre.csv')

## Create Genre Score

In [ ]:
#### If need to load csv made above ####
#df = pd.read_csv("/Workspace/Users/carrie.oh@curinos.com/2023-12-03 Artists_w_genre.csv")
#df

In [ ]:
###### IF artist_genre is saved as str not list #####
"""
import ast
for i in range(len(df)):
    string = df.artist_genre[i]
    df.artist_genre[i] = ast.literal_eval(string)

df
"""

Out[78]: '\nimport ast\nfor i in range(len(df)):\n    string = df.artist_genre[i]\n    df.artist_genre[i] = ast.literal_eval(string)\n\ndf\n'

In [ ]:
import itertools
genre_list = []
for i in range(len(df)):
    genre_list.append(df.artist_genre[i])

genre_list = list(itertools.chain.from_iterable(genre_list))
genre_list

Out[48]: ['canadian hip hop',
 'canadian pop',
 'hip hop',
 'pop rap',
 'rap',
 'pop',
 'chicago rap',
 'hip hop',
 'rap',
 'chicago rap',
 'melodic rap',
 'rap',
 'pop',
 'singer-songwriter pop',
 'uk pop',
 'canadian contemporary r&b',
 'canadian pop',
 'pop',
 'dance pop',
 'pop',
 'reggaeton',
 'trap latino',
 'urbano latino',
 'chicago rap',
 'rap',
 'atl hip hop',
 'atl trap',
 'rap',
 'trap',
 'canadian pop',
 'pop',
 'hip hop',
 'melodic rap',
 'philly rap',
 'rage rap',
 'rap',
 'conscious hip hop',
 'hip hop',
 'north carolina hip hop',
 'rap',
 'indie hip hop',
 'hip hop',
 'rap',
 'slap house',
 'baton rouge rap',
 'rap',
 'pop',
 'atl hip hop',
 'atl trap',
 'gangster rap',
 'melodic rap',
 'rap',
 'trap',
 'british soul',
 'pop',
 'pop soul',
 'uk pop',
 'atl hip hop',
 'hip hop',
 'rap',
 'southern hip hop',
 'trap',
 'detroit hip hop',
 'hip hop',
 'rap',
 'cloud rap',
 'dark trap',
 'new orleans rap',
 'underground hip hop',
 'atl hip hop',
 'hip hop',
 'rap',
 'hip hop',
 'pittsburgh rap',
 'pop rap',
 'rap',
 'contemporary country',
 'emo rap',
 'miami hip hop',
 'dfw rap',
 'melodic rap',
 'pop',
 'rap',
 'chicago drill',
 'chicago rap',
 'drill',
 'hip hop',
 'rap',
 'trap',
 'conscious hip hop',
 'hip hop',
 'rap',
 'west coast rap',
 'lgbtq+ hip hop',
 'houston rap',
 'pop',
 'r&b',
 'rap',
 'trap queen',
 'melodic rap',
 'rap',
 'trap',
 'atl hip hop',
 'plugg',
 'pluggnb',
 'rage rap',
 'rap',
 'pop',
 'hip hop',
 'rap',
 'east coast hip hop',
 'hip hop',
 'rap',
 'trap',
 'k-pop',
 'k-pop boy group',
 'pop',
 'australian hip hop',
 'hip hop',
 'new orleans rap',
 'pop rap',
 'rap',
 'trap',
 'deep underground hip hop',
 'kentucky hip hop',
 'pop rap',
 'rap',
 'atl hip hop',
 'melodic rap',
 'rap',
 'trap',
 'hip hop',
 'north carolina hip hop',
 'pop rap',
 'rap',
 'trap',
 'brooklyn drill',
 'rap',
 'reggaeton',
 'reggaeton colombiano',
 'trap latino',
 'urbano latino',
 'pop',
 'pop r&b',
 'barbadian pop',
 'pop',
 'urban contemporary',
 'dance pop',
 'pop',
 'uk pop',
 'contemporary country',
 'country',
 'cloud rap',
 'emo rap',
 'lgbtq+ hip hop',
 'dance pop',
 'pop',
 'hip hop',
 'ohio hip hop',
 'pop rap',
 'rap',
 'permanent wave',
 'pop',
 'pop',
 'r&b',
 'rap',
 'r&b',
 'rap',
 'ohio hip hop',
 'pop rap',
 'hip pop',
 'pop',
 'queens hip hop',
 'rap',
 'art pop',
 'pop',
 'brooklyn drill',
 'melodic rap',
 'nyc rap',
 'rap',
 'electropop',
 'etherpop',
 'indie poptimism',
 'pop',
 'pop rap',
 'rap',
 'trap',
 'hip hop',
 'rap',
 'r&b',
 'soul',
 'pop',
 'puerto rican pop',
 'reggaeton',
 'trap latino',
 'urbano latino',
 'melodic rap',
 'pluggnb',
 'rap',
 'modern rock',
 'pop',
 'rock',
 'brostep',
 'edm',
 'pop',
 'progressive electro house',
 'lgbtq+ hip hop',
 'neo soul',
 'melodic rap',
 'rap',
 'trap',
 'hip hop',
 'pop rap',
 'british invasion',
 'classic rock',
 'merseybeat',
 'psychedelic rock',
 'rock',
 'rap',
 'gauze pop',
 'indietronica',
 'modern rock',
 'pov: indie',
 'shiver pop',
 'detroit hip hop',
 'hip hop',
 'pop rap',
 'r&b',
 'rap',
 'trap',
 'florida drill',
 'florida rap',
 'melodic rap',
 'miami hip hop',
 'rap',
 'trap',
 'trap latino',
 'pop',
 'memphis hip hop',
 'rap',
 'southern hip hop',
 'tennessee hip hop',
 'trap',
 'florida rap',
 'pop',
 'hip hop',
 'philly rap',
 'pop rap',
 'rap',
 'southern hip hop',
 'trap',
 'modern alternative rock',
 'modern rock',
 'pop',
 'pov: indie',
 'corrido',
 'corridos tumbados',
 'sad sierreno',
 'sierreno',
 'hip hop',
 'pittsburgh rap',
 'pop rap',
 'rap',
 'southern hip hop',
 'trap',
 'glam rock',
 'mellow gold',
 'piano rock',
 'rock',
 'brooklyn drill',
 'nyc rap',
 'atl hip hop',
 'hip hop',
 'pop rap',
 'rap',
 'trap',
 'boy band',
 'pop',
 'post-teen pop',
 'talent show',
 'afrofuturism',
 'pop',
 'post-teen pop',
 'pov: indie',
 'corridos tumbados',
 'sad sierreno',
 'pop',
 'rap',
 'puerto rican pop',
 'reggaeton',
 'trap latino',
 'urbano latino',
 'pop',
 'r&b',
 'east coast hip hop',
 'gangster rap',
 'hip hop',
 'pop rap',
 'rap',
 'viral pop',
 'pop',
 'melodic rap',
 'rap',
 'trap',
 'modern rock',
 'pop',
 'pov: indie',
 'rock',
 'broadway',
 'show tunes',
 'r&b',
 'reggaeton',
 'trap latino',
 'urbano latino',
 'modern rock',
 'pop',
 'reggaeton',
 'reggaeton flow',
 'trap boricua',
 'trap latino',
 'urbano latino',
 'contemporary country',
 'country',
 'country road',
 'modern country rock',
 'pop',
 'musica mexicana',
 'norteno',
 'sierreno',
 'k-pop girl group',
 'baton rouge rap',
 'rap',
 'southern hip hop',
 'trap',
 'brooklyn indie',
 'pov: indie',
 'black americana',
 'contemporary country',
 'country',
 'country road',
 'hip hop',
 'pittsburgh rap',
 'pop rap',
 'rap',
 'southern hip hop',
 'trap',
 'hip hop',
 'miami hip hop',
 'pop rap',
 'rap',
 'trap',
 'alternative metal',
 'nu metal',
 'post-grunge',
 'rap metal',
 'rock',
 'emo',
 'modern rock',
 'pop',
 'rock',
 'alt z',
 'electropop',
 'pop',
 'contemporary country',
 'outlaw country',
 'reggaeton',
 'reggaeton colombiano',
 'trap latino',
 'urbano latino',
 'pop',
 'uk pop',
 'irish singer-songwriter',
 'modern rock',
 'pov: indie',
 'contemporary country',
 'country',
 'country pop',
 'country road',
 'modern country rock',
 'grunge',
 'permanent wave',
 'rock',
 'reggaeton',
 'trap latino',
 'urbano latino',
 'r&b',
 'rap',
 'canadian pop',
 'pop',
 'viral pop',
 'album rock',
 'classic rock',
 'rock',
 'soft rock',
 'yacht rock',
 'bedroom pop',
 'pop',
 'pov: indie',
 'garage rock',
 'modern rock',
 'permanent wave',
 'rock',
 'sheffield indie',
 'conscious hip hop',
 'hip hop',
 'pop rap',
 'rap',
 'melodic rap',
 'rap',
 'reggaeton',
 'trap latino',
 'urbano latino',
 'latin hip hop',
 'reggaeton',
 'trap latino',
 'urbano latino',
 'big room',
 'dance pop',
 'edm',
 'pop',
 'pop dance',
 'chicago drill',
 'chicago rap',
 'drill',
 'trap',
 'atl hip hop',
 'hip hop',
 'rap',
 'australian rock',
 'hard rock',
 'rock',
 'boston hip hop',
 'hip hop',
 'pop rap',
 'rap',
 'neo mellow',
 'singer-songwriter',
 'melodic rap',
 'hard rock',
 'metal',
 'old school thrash',
 'rock',
 'thrash metal',
 'australian psych',
 'modern rock',
 'neo-psychedelic',
 'rock',
 'classic texas country',
 'contemporary country',
 'memphis hip hop',
 'rap',
 'southern hip hop',
 'tennessee hip hop',
 'trap',
 'colombian pop',
 'chicago rap',
 'alternative rock',
 'funk metal',
 'funk rock',
 'permanent wave',
 'rock',
 'kentucky indie',
 'kentucky roots',
 'outlaw country',
 'emo',
 'modern rock',
 'pop punk',
 'pov: indie',
 'rock',
 'modern rock',
 'permanent wave',
 'punk',
 'rock',
 'alternative hip hop',
 'modern rock',
 'rock',
 'atl hip hop',
 'dirty south rap',
 'hip hop',
 'pop rap',
 'rap',
 'southern hip hop',
 'trap',
 'contemporary country',
 'country',
 'country road',
 'modern country rock',
 'dance pop',
 'pop',
 'r&b',
 'rap',
 'adult standards',
 'easy listening',
 'lounge',
 'canadian hip hop',
 'canadian trap',
 'melodic rap',
 'pop rap',
 'r&b',
 'rap',
 'trap',
 'r&b',
 'dance pop',
 'miami hip hop',
 'pop',
 'pop',
 'post-teen pop',
 'hip hop',
 'pop rap',
 'rap',
 'trap',
 'dance pop',
 'pop',
 'urban contemporary',
 'indie pop rap',
 'oakland hip hop',
 'pop rap',
 'rap',
 'bedroom pop',
 'indie pop',
 'pov: indie',
 'candy pop',
 'modern rock',
 'pixie',
 'pop',
 'pop emo',
 'pop punk',
 'rock',
 'dance pop',
 'pop',
 'kentucky hip hop',
 'r&b',
 'rap',
 'edmonton indie',
 'lo-fi indie',
 'pov: indie',
 'pov: indie',
 'latin pop',
 'reggaeton',
 'reggaeton colombiano',
 'trap latino',
 'urbano latino',
 'atl hip hop',
 'melodic rap',
 'r&b',
 'rap',
 'trap',
 'contemporary country',
 'country',
 'country road',
 'modern country rock',
 'comic',
 'pov: indie',
 'atl hip hop',
 'contemporary r&b',
 'dance pop',
 'pop',
 'r&b',
 'rap',
 'south carolina hip hop',
 'urban contemporary',
 'art pop',
 'metropopolis',
 'nz pop',
 'pop',
 'dance pop',
 'edm',
 'electro house',
 'house',
 'pop',
 'pop dance',
 'progressive house',
 'uk dance',
 'hip hop',
 'miami hip hop',
 'pop rap',
 'rap',
 'g funk',
 'gangster rap',
 'hip hop',
 'rap',
 'west coast rap',
 'classic texas country',
 'contemporary country',
 'country dawn',
 'album rock',
 'british invasion',
 'classic rock',
 'rock',
 'contemporary country',
 'country',
 'country road',
 'dance pop',
 'edm',
 'electro house',
 'moombahton',
 'pop dance',
 'canadian contemporary r&b',
 'pop',
 'post-teen pop',
 'pop',
 'r&b',
 'rap',
 'memphis hip hop',
 'rap',
 'aesthetic rap',
 'cloud rap',
 'florida rap',
 'underground hip hop',
 'corrido',
 'corridos tumbados',
 'musica mexicana',
 'sad sierreno',
 'sierreno',
 'pop reggaeton',
 'reggaeton',
 'trap latino',
 'urbano latino',
 'r&b',
 'rap',
 'bedroom pop',
 'alternative metal',
 'nu metal',
 'rap metal',
 'rock',
 'bedroom pop',
 'indie pop',
 'pov: indie',
 'folk-pop',
 'modern rock',
 'stomp and holler',
 'contemporary country',
 'country',
 'country road',
 'album rock',
 'classic rock',
 'hard rock',
 'rock',
 'atl hip hop',
 'melodic rap',
 'rap',
 'trap',
 'afrofuturism',
 'pop',
 'panamanian pop',
 'reggaeton',
 'trap latino',
 'urbano latino',
 'dfw rap',
 'melodic rap',
 'pop',
 'rap',
 'indie pop',
 'la indie',
 'pov: indie',
 'pop',
 'canadian hip hop',
 'canadian pop',
 'hip hop',
 'pop rap',
 'rap',
 'chicago rap',
 'melodic rap',
 'rap',
 'chicago rap',
 'hip hop',
 'rap',
 'british soul',
 'pop',
 'pop soul',
 'uk pop',
 'canadian contemporary r&b',
 'canadian pop',
 'pop',
 'dance pop',
 'pop',
 'chicago rap',
 'rap',
 'reggaeton',
 'trap latino',
 'urbano latino',
 'pop',
 'canadian pop',
 'pop',
 'atl hip hop',
 'atl trap',
 'rap',
 'trap',
 'hip hop',
 'melodic rap',
 'philly rap',
 'rage rap',
 'rap',
 'conscious hip hop',
 'hip hop',
 'north carolina hip hop',
 'rap',
 'contemporary country',
 'baton rouge rap',
 'rap',
 'hip hop',
 'rap',
 'slap house',
 'dfw rap',
 'melodic rap',
 'pop',
 'rap',
 'dance pop',
 'pop',
 'cloud rap',
 'dark trap',
 'new orleans rap',
 'underground hip hop',
 'atl hip hop',
 'hip hop',
 'rap',
 'southern hip hop',
 'trap',
 'atl hip hop',
 'plugg',
 'pluggnb',
 'rage rap',
 'rap',
 'indie hip hop',
 'k-pop',
 'k-pop boy group',
 'pop',
 'emo rap',
 'miami hip hop',
 'atl hip hop',
 'hip hop',
 'rap',
 'detroit hip hop',
 'hip hop',
 'rap',
 'conscious hip hop',
 'hip hop',
 'rap',
 'west coast rap',
 'pop',
 'singer-songwriter pop',
 'uk pop',
 'chicago drill',
 'chicago rap',
 'drill',
 'hip hop',
 'rap',
 'trap',
 'hip hop',
 'rap',
 'hip hop',
 'pittsburgh rap',
 'pop rap',
 'rap',
 'melodic rap',
 'rap',
 'trap',
 'pop',
 'british invasion',
 'classic rock',
 'merseybeat',
 'psychedelic rock',
 'rock',
 'atl hip hop',
 'atl trap',
 'gangster rap',
 'melodic rap',
 'rap',
 'trap',
 'adult standards',
 'easy listening',
 'lounge',
 'adult standards',
 'canadian pop',
 'jazz pop',
 'lounge',
 'lgbtq+ hip hop',
 'a cappella',
 'viral pop',
 'hip hop',
 'north carolina hip hop',
 'pop rap',
 'rap',
 'trap',
 'australian hip hop',
 'brooklyn drill',
 'rap',
 'atl hip hop',
 'melodic rap',
 'rap',
 'trap',
 'contemporary country',
 'country',
 'deep underground hip hop',
 'kentucky hip hop',
 'pop rap',
 'rap',
 'hip hop',
 'new orleans rap',
 'pop rap',
 'rap',
 'trap',
 'adult standards',
 'easy listening',
 'lounge',
 'escape room',
 'hip hop',
 'indie soul',
 'neo soul',
 'pop',
 'r&b',
 'rap',
 'reggaeton',
 'reggaeton flow',
 'trap boricua',
 'trap latino',
 'urbano latino',
 'memphis hip hop',
 'rap',
 'southern hip hop',
 'tennessee hip hop',
 'trap',
 'pop',
 'pop r&b',
 'florida rap',
 'houston rap',
 'pop',
 'r&b',
 'rap',
 'trap queen',
 'r&b',
 'rap',
 'reggaeton',
 'reggaeton colombiano',
 'trap latino',
 'urbano latino',
 'cloud rap',
 'emo rap',
 'lgbtq+ hip hop',
 'dance pop',
 'pop',
 'urban contemporary',
 'dance pop',
 'pop',
 'uk pop',
 'hip hop',
 'ohio hip hop',
 'pop rap',
 'rap',
 'modern rock',
 'pop',
 'rock',
 'hip hop',
 'rap',
 'florida drill',
 'florida rap',
 'melodic rap',
 'miami hip hop',
 'rap',
 'trap',
 'trap latino',
 'barbadian pop',
 'pop',
 'urban contemporary',
 'ohio hip hop',
 'pop rap',
 'dance pop',
 'pop',
 'pop',
 'r&b',
 'rap',
 'brooklyn drill',
 'melodic rap',
 'nyc rap',
 'rap',
 'hip pop',
 'pop',
 'queens hip hop',
 'rap',
 'permanent wave',
 'pop',
 'electropop',
 'etherpop',
 'indie poptimism',
 'pop',
 'lgbtq+ hip hop',
 'neo soul',
 'hip hop',
 'pop rap',
 'broadway',
 'show tunes',
 'adult standards',
 'lounge',
 'soul',
 'swing',
 'vocal jazz',
 'melodic rap',
 'rap',
 'trap',
 'gauze pop',
 'indietronica',
 'modern rock',
 'pov: indie',
 'shiver pop',
 'modern alternative rock',
 'modern rock',
 'pop',
 'pov: indie',
 'puerto rican pop',
 'reggaeton',
 'trap latino',
 'urbano latino',
 'melodic rap',
 'pluggnb',
 'rap',
 'rap',
 'memphis hip hop',
 'rap',
 'southern hip hop',
 'tennessee hip hop',
 'trap',
 'pop',
 'brostep',
 'edm',
 'pop',
 'progressive electro house',
 'contemporary country',
 'outlaw country',
 'art pop',
 'pop',
 'east coast hip hop',
 'hip hop',
 'rap',
 'trap',
 'glam rock',
 'mellow gold',
 'piano rock',
 'rock',
 'pop rap',
 'rap',
 'trap',
 'pop',
 'memphis hip hop',
 'rap',
 'southern hip hop',
 'tennessee hip hop',
 'trap',
 'viral pop',
 'boy band',
 'pop',
 'post-teen pop',
 'talent show',
 'colombian pop',
 'pop',
 'rap',
 'modern rock',
 'pop',
 'pov: indie',
 'rock',
 'corrido',
 'corridos tumbados',
 'sad sierreno',
 'sierreno',
 'puerto rican pop',
 'reggaeton',
 'trap latino',
 'urbano latino',
 'contemporary country',
 'country',
 'country road',
 'modern country rock',
 'brooklyn indie',
 'pov: indie',
 'dance pop',
 'pop',
 'talent show',
 'hip hop',
 'philly rap',
 'pop rap',
 'rap',
 'southern hip hop',
 'trap',
 'melodic rap',
 'rap',
 'trap',
 'brooklyn drill',
 'nyc rap',
 'hip hop',
 'pittsburgh rap',
 'pop rap',
 'rap',
 'southern hip hop',
 'trap',
 'east coast hip hop',
 'gangster rap',
 'hip hop',
 'pop rap',
 'rap',
 'corridos tumbados',
 'sad sierreno',
 ...]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          5000 non-null   int64
 1   month         5000 non-null   int64
 2   week          5000 non-null   int64
 3   rank          5000 non-null   int64
 4   track title   0 non-null      float64
 5   artist name   5000 non-null   object
 6   artist_genre  5000 non-null   object
dtypes: float64(1), int64(4), object(2)
memory usage: 273.6+ KB

In [ ]:
key = genre_list
value = [0]*len(key)
key_value = zip(key,value)
genre_rank = dict(key_value)

for i in range(len(df)):
    rank_inverse = 1/df.iloc[i]['rank']
    for genre in df.artist_genre[i]:
        genre_rank[genre] += rank_inverse

genre_rank_sorted = dict(sorted(genre_rank.items(), key=lambda item: item[1], reverse=True))

In [ ]:
genre_rank_sorted

Out[76]: {'rap': 64.89774784006376,
 'pop': 45.27196555621168,
 'hip hop': 41.87079420966266,
 'pop rap': 20.06075270993361,
 'canadian pop': 19.936482705439253,
 'canadian hip hop': 14.53780997247489,
 'trap': 13.646922865974455,
 'trap latino': 11.914556989222483,
 'urbano latino': 11.362530363598738,
 'chicago rap': 11.300946371270559,
 'melodic rap': 11.300841521062615,
 'atl hip hop': 11.247365896464979,
 'reggaeton': 11.234494160718308,
 'contemporary country': 7.176189039835229,
 'r&b': 5.686872267141955,
 'canadian contemporary r&b': 4.586181849622131,
 'southern hip hop': 4.518461948800804,
 'rock': 4.385289764348169,
 'dance pop': 3.826219901899467,
 'conscious hip hop': 3.6211093638587566,
 'sad sierreno': 3.4162512018257756,
 'corridos tumbados': 3.1691228103697977,
 'sierreno': 3.0838064129078138,
 'modern rock': 2.979793919105793,
 'corrido': 2.978059098139599,
 'atl trap': 2.9240069390019836,
 'rage rap': 2.4382490138866353,
 'new orleans rap': 2.334641095169594,
 'pov: indie': 2.2681702648284907,
 'country': 2.228820098147684,
 'cloud rap': 2.160064779006404,
 'miami hip hop': 2.1520758315551416,
 'slap house': 2.0858574923835183,
 'west coast rap': 2.043034015803363,
 'north carolina hip hop': 2.0221583300632266,
 'uk pop': 1.9363084567141677,
 'modern country pop': 1.8951003346537547,
 'underground hip hop': 1.8687431772138254,
 'philly rap': 1.7945985755192166,
 'classic oklahoma country': 1.7895450606025505,
 'baton rouge rap': 1.786179282870528,
 'dark trap': 1.7286885547382769,
 'dfw rap': 1.5953606276176309,
 'emo rap': 1.4756507331404813,
 'country road': 1.3718354858583413,
 'permanent wave': 1.3428632143451102,
 'detroit hip hop': 1.3324891862569304,
 'florida rap': 1.2210233150915848,
 'reggaeton colombiano': 1.180599921882155,
 'gangster rap': 1.1725633510695366,
 'lgbtq+ hip hop': 1.1410568809195605,
 'urban contemporary': 1.1220513804865122,
 'pittsburgh rap': 1.104135676762397,
 'drill': 1.0217428510737931,
 'chicago drill': 1.0150761844071263,
 'pluggnb': 0.9183918436960531,
 'memphis hip hop': 0.8996519792978954,
 'musica mexicana': 0.8940118366425175,
 'classic rock': 0.8896660985169577,
 'modern country rock': 0.8863665283025207,
 'indie hip hop': 0.8862336444194658,
 'edm': 0.8797625711694008,
 'singer-songwriter pop': 0.8453155171973117,
 'art pop': 0.8156884297271059,
 'broadway': 0.8138513374251592,
 'show tunes': 0.8068090839040325,
 'brooklyn drill': 0.7985809266848121,
 'barbadian pop': 0.7720053238088211,
 'plugg': 0.770177331899154,
 'k-pop': 0.7615373629275309,
 'east coast hip hop': 0.7465152842368266,
 'tennessee hip hop': 0.7393300299630434,
 'ohio hip hop': 0.7384153301956861,
 'kentucky hip hop': 0.7187574779871437,
 'florida drill': 0.6796715998262475,
 'puerto rican pop': 0.6586396273010742,
 'queens hip hop': 0.6359188551613874,
 'k-pop boy group': 0.6292508129755985,
 'outlaw country': 0.6225122788265349,
 'colombian pop': 0.6139023829936776,
 'electropop': 0.6077136246331545,
 'pop dance': 0.6055884458530658,
 'neo soul': 0.6030009676860313,
 'hip pop': 0.5925504918369411,
 'afrofuturism': 0.5730603863782072,
 'viral pop': 0.5636080410209827,
 'alternative metal': 0.5435701554972174,
 'pop soul': 0.5394163308014271,
 'deep underground hip hop': 0.5358716266876449,
 'british soul': 0.5339518499271101,
 'piano rock': 0.5002735020428478,
 'bedroom pop': 0.47707427391026447,
 'pop r&b': 0.46717131929979405,
 'trap queen': 0.4638805768465087,
 'nu metal': 0.4620392248381215,
 'alt z': 0.45784827370772213,
 'rap metal': 0.45105649630709904,
 'album rock': 0.44945539011100144,
 'nyc rap': 0.44303966493561886,
 'post-teen pop': 0.4340690733174228,
 'hard rock': 0.4320227471132288,
 'british invasion': 0.4192389938908561,
 'modern alternative rock': 0.38937106650473413,
 'psychedelic rock': 0.38792738926286746,
 'indie poptimism': 0.3825171861921926,
 'merseybeat': 0.37653054531196156,
 'latin hip hop': 0.3394225830817253,
 'latin pop': 0.33467586022544815,
 'alternative rock': 0.3323850199395951,
 'soft rock': 0.330638709423061,
 'brostep': 0.33000614537369505,
 'australian hip hop': 0.3267133704470268,
 'houston rap': 0.3244626659220333,
 'mellow gold': 0.3242390600739953,
 'kentucky indie': 0.32373270516649116,
 'kentucky roots': 0.32373270516649116,
 'etherpop': 0.31910777042155064,
 'electro house': 0.31563681843996916,
 'k-pop girl group': 0.3132208691822041,
 'reggaeton flow': 0.30165391074862985,
 'garage rock': 0.30143283011644784,
 'sheffield indie': 0.30143283011644784,
 'pop punk': 0.2870537553510714,
 'post-grunge': 0.28532148165611654,
 'emo': 0.28434054739106707,
 'boy band': 0.2800025925843438,
 'norteno': 0.2798939989779931,
 'adult standards': 0.27838008910939727,
 'progressive electro house': 0.2741741253163355,
 'yacht rock': 0.2669880432069003,
 'big room': 0.26382825659656683,
 'canadian trap': 0.2621013510711177,
 'house': 0.2618715113305556,
 'lounge': 0.25966234223631063,
 'soul': 0.2552052893844054,
 'brooklyn indie': 0.2536580156091622,
 'trap boricua': 0.24849608714069651,
 'talent show': 0.23891178363372342,
 'glam rock': 0.23882296667249595,
 'edmonton indie': 0.22848062762371432,
 'lo-fi indie': 0.22848062762371432,
 'classic texas country': 0.22410069702693236,
 'metal': 0.22196956887250505,
 'old school thrash': 0.22196956887250505,
 'thrash metal': 0.22196956887250505,
 'funk metal': 0.217698324844774,
 'funk rock': 0.217698324844774,
 'pop reggaeton': 0.2168844472589701,
 'australian psych': 0.215854496703772,
 'neo-psychedelic': 0.215854496703772,
 'musica chihuahuense': 0.21519344058774945,
 'progressive house': 0.2130817447943228,
 'uk dance': 0.2130817447943228,
 'grunge': 0.2089746745216111,
 'escape room': 0.19283241947278187,
 'g funk': 0.18851877848146392,
 'irish singer-songwriter': 0.18681614505196445,
 'punk': 0.18271092421536209,
 'easy listening': 0.1823849204328642,
 'alternative hip hop': 0.18003012740486796,
 'movie tunes': 0.17433444673347875,
 'black americana': 0.1697084387756832,
 'candy pop': 0.16619883723879708,
 'pixie': 0.1644362050413823,
 'dirty south rap': 0.16343104969996208,
 'pop emo': 0.15718982822978808,
 'folk-pop': 0.1547141718853338,
 'stomp and holler': 0.1547141718853338,
 'sacramento indie': 0.15324133351606248,
 'indietronica': 0.15281706279634316,
 'gauze pop': 0.14689990303302955,
 'shiver pop': 0.14689990303302955,
 'country pop': 0.14670065609936955,
 'minnesota hip hop': 0.14446408418200865,
 'bronx drill': 0.143879359134725,
 'australian rock': 0.13834878308957685,
 'singer-songwriter': 0.13661910363579824,
 'contemporary r&b': 0.13394188327415182,
 'south carolina hip hop': 0.13394188327415182,
 'ambient pop': 0.12662733138171503,
 'dream pop': 0.12662733138171503,
 'el paso indie': 0.12662733138171503,
 'shoegaze': 0.12662733138171503,
 'art rock': 0.11644818404195187,
 'indie pop': 0.10999536979461383,
 'moombahton': 0.1025550736456463,
 'country rap': 0.09330857007140544,
 'nashville hip hop': 0.09330857007140544,
 'indie soul': 0.09113531933331255,
 'country dawn': 0.08577854753738191,
 'heartland rock': 0.0854160934014993,
 'bachata': 0.0832472108993169,
 'melancholia': 0.08111051676343016,
 'oxford indie': 0.07542869858161198,
 'hollywood': 0.07217684051161187,
 'hardcore hip hop': 0.06940627259307287,
 'country rock': 0.06368016309399474,
 'southern rock': 0.06368016309399474,
 'swamp rock': 0.06368016309399474,
 'bedroom r&b': 0.062180436399091904,
 'modern indie pop': 0.06129099401797074,
 'meme rap': 0.055588228731915906,
 'jazz pop': 0.054093567251461985,
 'rockabilly': 0.053329786765456445,
 'socal pop punk': 0.052451644324597015,
 'rap latina': 0.051098577562995,
 'aesthetic rap': 0.050417759865025474,
 'neo mellow': 0.050338802903210536,
 'vocal jazz': 0.05007542762115933,
 'a cappella': 0.04880952380952381,
 'dutch edm': 0.048789766536232744,
 'trance': 0.048789766536232744,
 'rock-and-roll': 0.0446341345915434,
 'sigilkore': 0.04434984298131904,
 'sped up': 0.04434984298131904,
 'trop rock': 0.041666666666666664,
 'detroit trap': 0.04061228442139621,
 'alternative pop rock': 0.038628229246926805,
 'gen z singer-songwriter': 0.036591663322837246,
 'transpop': 0.03550870924359775,
 'afro r&b': 0.03338431685714662,
 'alte': 0.03338431685714662,
 'nigerian pop': 0.03338431685714662,
 'argentine hip hop': 0.03264161354637182,
 'pop venezolano': 0.03264161354637182,
 'trap argentino': 0.03264161354637182,
 'baroque pop': 0.029622641509433965,
 'new wave pop': 0.029622641509433965,
 'trap dominicano': 0.029289551344179324,
 'swing': 0.028612012987012988,
 'christian a cappella': 0.024129353233830846,
 'college a cappella': 0.024129353233830846,
 'lds': 0.024129353233830846,
 'lds youth': 0.024129353233830846,
 'chicago bop': 0.02326409309542762,
 'latin viral pop': 0.02180902621881567,
 'metropopolis': 0.02157208322534298,
 'nz pop': 0.02157208322534298,
 'dutch pop': 0.01982371916561905,
 'australian pop': 0.01967738850722543,
 'speedrun': 0.019545306057292194,
 'video game music': 0.019545306057292194,
 'alternative r&b': 0.019186940227402655,
 'phonk': 0.018738404452690167,
 'screamo': 0.018175338560228082,
 'reggae': 0.0170808518713143,
 'roots reggae': 0.0170808518713143,
 'jazz trio': 0.01664259679526855,
 'la indie': 0.01556652169064347,
 'scorecore': 0.014285714285714285,
 'australian dance': 0.014090796328454478,
 'american folk revival': 0.01328958843805806,
 'indie pop rap': 0.012461180124223602,
 'cali rap': 0.012424277501254005,
 'texas latin rap': 0.012293233082706766,
 'scam rap': 0.012047762047762048,
 'bedroom soul': 0.011606252078483538,
 'progressive rock': 0.011396843950905903,
 'symphonic rock': 0.011396843950905903,
 'comic': 0.011029300366633337,
 'modern alternative pop': 0.010940722805129584,
 'panamanian pop': 0.010286107144745888,
 'modern power pop': 0.01017871017871018,
 'tropical house': 0.010152545866831581,
 'virginia hip hop': 0.00980392156862745,
 'melodic dubstep': 0.008928571428571428,
 'indiana hip hop': 0.008547008547008548,
 'drift phonk': 0.00819672131147541,
 'game mood': 0.00819672131147541,
 'boston hip hop': 0.007352941176470588,
 'swancore': 0.007246376811594203,
 'complextro': 0.007042253521126761,
 'electro': 0.007042253521126761,
 'orchestral soundtrack': 0.007042253521126761,
 'vancouver indie': 0.00641025641025641,
 'oakland hip hop': 0.006211180124223602,
 'westcoast flow': 0.005952380952380952,
 'uk alternative pop': 0.005917159763313609,
 'boston folk': 0.005780346820809248,
 'groove metal': 0.005747126436781609,
 'sad rap': 0.005714285714285714,
 'chamber pop': 0.005681818181818182,
 'eau claire indie': 0.005681818181818182,
 'indie folk': 0.005681818181818182,
 'melodic drill': 0.005555555555555556,
 'europop': 0.005434782608695652,
 'swedish pop': 0.005434782608695652,
 'mexican hip hop': 0.005235602094240838,
 'norwegian indie': 0.005154639175257732,
 'instrumental hip hop': 0.005128205128205128,
 'mariachi': 0.005076142131979695,
 'ranchera': 0.005076142131979695,
 'rap rock': 0.005025125628140704,
 'reggae fusion': 0.005025125628140704,
 'ska mexicano': 0.005025125628140704,
 'ska punk': 0.005025125628140704,
 'prog metal': 0.005}